# Generated by Django 4.0.1 on 2022-01-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realistsocialism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='year',
            field=models.IntegerField(default=1950),
        ),
    ]
