# Generated by Django 4.0.1 on 2022-01-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realistsocialism', '0002_poster_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
