# Generated by Django 4.0.1 on 2022-01-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realistsocialism', '0004_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='image_url',
            field=models.URLField(default='none'),
        ),
    ]
