# Generated by Django 4.0.1 on 2022-01-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realistsocialism', '0005_poster_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='image',
        ),
    ]
